import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, Check, Clock3, Link2, Pencil, Plus, Save, Send, Trash2, X } from 'lucide-react';
import { toast } from 'sonner';
import DashboardLayout from '@/layouts/DashboardLayout';
import { calendarApi, type CalendarCatalog } from '@/api/calendar';
import { scheduleApi, type ScheduleEntry, type ScheduleEntryInput, type WeeklySchedule } from '@/api/schedule';
import { teachingAssignmentsApi } from '@/api/teachingAssignments';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const DAYS = [
  { value: 1, label: 'Lunes' }, { value: 2, label: 'Martes' }, { value: 3, label: 'Miércoles' },
  { value: 4, label: 'Jueves' }, { value: 5, label: 'Viernes' }, { value: 6, label: 'Sábado' }, { value: 7, label: 'Domingo' },
];
const EMPTY_CATALOG: CalendarCatalog = { years: [], grades: [], groups: [], areas: [], teachers: [], aulas: [] };
const emptyEntry = (): ScheduleEntryInput => ({ teaching_assignment_id: '', aula_id: '', weekday: 1, start_time: '07:00', end_time: '08:00' });

const ScheduleManagementPage = () => {
  const queryClient = useQueryClient();
  const [schoolYearId, setSchoolYearId] = useState('');
  const [workingSchedule, setWorkingSchedule] = useState<WeeklySchedule | null>(null);
  const [entryForm, setEntryForm] = useState<ScheduleEntryInput | null>(null);
  const [editingEntryId, setEditingEntryId] = useState<string | null>(null);
  const catalogQuery = useQuery({ queryKey: ['schedule-catalog', schoolYearId], queryFn: () => calendarApi.catalog('admin', schoolYearId || undefined), staleTime: 60_000 });
  const catalog = catalogQuery.data || EMPTY_CATALOG;
  const schedulesQuery = useQuery({ queryKey: ['schedules', schoolYearId], enabled: Boolean(schoolYearId), queryFn: () => scheduleApi.list(schoolYearId) });
  const assignmentsQuery = useQuery({ queryKey: ['schedule-assignments', schoolYearId], enabled: Boolean(schoolYearId), queryFn: () => teachingAssignmentsApi.list({ school_year_id: schoolYearId, status: 'active' }), staleTime: 30_000 });
  const baseSchedule = useMemo(() => { const schedules = schedulesQuery.data?.schedules || []; return schedules.find((item) => item.status === 'draft') || schedules.find((item) => item.status === 'published') || null; }, [schedulesQuery.data]);
  useEffect(() => { if (!schoolYearId && catalog.years[0]?.id) setSchoolYearId(catalog.years[0].id); }, [catalog.years, schoolYearId]);
  useEffect(() => { setWorkingSchedule((current) => current && current.school_year._id !== schoolYearId ? null : current); setEntryForm(null); setEditingEntryId(null); }, [schoolYearId]);
  useEffect(() => { if (baseSchedule) setWorkingSchedule((current) => current?.id === baseSchedule.id ? current : baseSchedule); }, [baseSchedule]);
  const schedule = workingSchedule || baseSchedule;
  const draft = schedule?.status === 'draft' ? schedule : null;
  const entriesQuery = useQuery({ queryKey: ['schedule-entries', draft?.id], enabled: Boolean(draft?.id), queryFn: () => scheduleApi.entries(draft!.id) });
  const entries = entriesQuery.data?.entries || [];
  const assignments = assignmentsQuery.data?.assignments || [];
  const selectedAssignment = assignments.find((item) => item.id === entryForm?.teaching_assignment_id);

  const createDraftMutation = useMutation({ mutationFn: () => scheduleApi.createDraft(schoolYearId), onSuccess: (created) => { setWorkingSchedule(created); void queryClient.invalidateQueries({ queryKey: ['schedules'] }); toast.success('Borrador listo para editar'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo crear el borrador') });
  const saveSettingsMutation = useMutation({ mutationFn: () => scheduleApi.update(draft!.id, { school_days: draft!.school_days, availability_windows: draft!.availability_windows.map(({ window_id, group_id, start_time, end_time }) => ({ window_id, group_id, start_time, end_time })) }), onSuccess: (updated) => { setWorkingSchedule(updated); void queryClient.invalidateQueries({ queryKey: ['schedules'] }); toast.success('Configuración guardada'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo guardar la configuración') });
  const publishMutation = useMutation({ mutationFn: () => scheduleApi.publish(draft!.id), onSuccess: (published) => { setWorkingSchedule(published); void queryClient.invalidateQueries({ queryKey: ['schedules'] }); toast.success('Horario publicado y sesiones generadas'); }, onError: (error: any) => { const errors = error?.response?.data?.details?.errors; toast.error(Array.isArray(errors) ? errors.join(' · ') : error?.response?.data?.message || 'No se pudo publicar el horario'); } });
  const entryMutation = useMutation({ mutationFn: () => editingEntryId ? scheduleApi.updateEntry(draft!.id, editingEntryId, entryForm!) : scheduleApi.createEntry(draft!.id, entryForm!), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['schedule-entries', draft?.id] }); setEntryForm(null); setEditingEntryId(null); toast.success(editingEntryId ? 'Entrada actualizada' : 'Entrada agregada'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo guardar la entrada') });
  const archiveMutation = useMutation({ mutationFn: (entryId: string) => scheduleApi.archiveEntry(draft!.id, entryId), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['schedule-entries', draft?.id] }); toast.success('Entrada retirada del borrador'); }, onError: (error: any) => toast.error(error?.response?.data?.message || 'No se pudo retirar la entrada') });

  const updateDraft = (changes: Partial<WeeklySchedule>) => setWorkingSchedule((current) => current ? { ...current, ...changes } : current);
  const openEntry = (entry?: ScheduleEntry) => { setEditingEntryId(entry?.id || null); setEntryForm(entry ? { teaching_assignment_id: entry.teaching_assignment_id, aula_id: entry.aula.id, weekday: entry.weekday, start_time: entry.start_time, end_time: entry.end_time, entry_key: entry.entry_key } : emptyEntry()); };
  const saveEntry = () => { if (!entryForm || !draft) return; if (!entryForm.teaching_assignment_id || !entryForm.aula_id) return toast.error('Selecciona una asignación y un aula'); if (!draft.school_days.includes(entryForm.weekday)) return toast.error('Selecciona un día lectivo'); if (entryForm.start_time >= entryForm.end_time) return toast.error('La hora inicial debe ser anterior a la final'); entryMutation.mutate(); };
  const groupedEntries = DAYS.map((day) => ({ day, entries: entries.filter((entry) => entry.weekday === day.value).sort((a, b) => a.start_time.localeCompare(b.start_time)) }));

  return <DashboardLayout><div className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><CalendarDays className="h-4 w-4" />Organización académica</div><h1 className="mt-2 text-3xl font-display font-extrabold tracking-tight">Horario académico</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Convierte asignaciones docentes en entradas de horario. Al publicar, el sistema materializa las clases del año escolar.</p></div><div className="flex flex-wrap items-center gap-3"><Select value={schoolYearId} onValueChange={setSchoolYearId}><SelectTrigger className="w-48"><SelectValue placeholder="Año escolar" /></SelectTrigger><SelectContent>{catalog.years.map((year) => <SelectItem key={year.id} value={year.id}>{year.name}</SelectItem>)}</SelectContent></Select>{!draft && <Button onClick={() => createDraftMutation.mutate()} disabled={!schoolYearId || createDraftMutation.isPending}><Plus className="h-4 w-4" />Crear borrador</Button>}</div></header>
    {schedule && <div className="flex flex-wrap items-center gap-2"><Badge variant={schedule.status === 'published' ? 'default' : 'secondary'}>{schedule.status === 'published' ? 'Publicado' : `Borrador v${schedule.version}`}</Badge>{schedule.status === 'published' && <span className="text-sm text-muted-foreground">Crea un borrador para proponer cambios.</span>}</div>}
    {draft && <>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Clock3 className="h-4 w-4" />Días lectivos</CardTitle><CardDescription>La publicación solo generará sesiones en estos días.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{DAYS.map((day) => { const active = draft.school_days.includes(day.value); return <Button key={day.value} type="button" variant={active ? 'default' : 'outline'} size="sm" onClick={() => updateDraft({ school_days: active && draft.school_days.length > 1 ? draft.school_days.filter((value) => value !== day.value) : active ? draft.school_days : [...draft.school_days, day.value].sort() })}>{active && <Check className="h-4 w-4" />}{day.label}</Button>; })}</CardContent></Card>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><Card><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="text-base">Entradas del horario</CardTitle><CardDescription>Cada entrada nace de una asignación docente activa.</CardDescription></div><Button variant="outline" onClick={() => openEntry()}><Plus className="h-4 w-4" />Agregar entrada</Button></CardHeader><CardContent className="space-y-5">{entriesQuery.isLoading && <p className="py-8 text-sm text-muted-foreground">Cargando entradas…</p>}{!entriesQuery.isLoading && entries.length === 0 && <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Todavía no hay entradas. Crea asignaciones y después programa sus días y aulas.</p>}{groupedEntries.map(({ day, entries: dayEntries }) => dayEntries.length > 0 && <section key={day.value} aria-labelledby={`day-${day.value}`}><div className="mb-2 flex items-center justify-between border-b pb-2"><h2 id={`day-${day.value}`} className="font-semibold">{day.label}</h2><span className="text-xs text-muted-foreground">{dayEntries.length} {dayEntries.length === 1 ? 'entrada' : 'entradas'}</span></div><div className="space-y-2">{dayEntries.map((entry) => <div key={entry.id} className="flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold">{entry.area.name} · {entry.group.name}</p><p className="text-sm text-muted-foreground">{entry.start_time} – {entry.end_time} · {entry.aula.name}</p><p className="text-xs text-muted-foreground">{entry.teacher.name}{entry.campus ? ` · ${entry.campus.name}` : ''}</p></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" onClick={() => openEntry(entry)}><Pencil className="h-4 w-4" />Editar</Button><Button variant="ghost" size="icon" aria-label={`Retirar entrada de ${entry.area.name}`} onClick={() => archiveMutation.mutate(entry.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div>)}</div></section>)}</CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">{editingEntryId ? 'Editar entrada' : 'Nueva entrada'}</CardTitle><CardDescription>Selecciona una asignación y completa únicamente cuándo y dónde ocurre.</CardDescription></CardHeader><CardContent>{entryForm ? <div className="space-y-4"><Field label="Asignación docente"><Select value={entryForm.teaching_assignment_id} onValueChange={(value) => setEntryForm({ ...entryForm, teaching_assignment_id: value })}><SelectTrigger><SelectValue placeholder="Selecciona una asignación" /></SelectTrigger><SelectContent>{assignments.map((assignment) => <SelectItem key={assignment.id} value={assignment.id}>{assignment.teacher.name} · {assignment.area.name} · {assignment.group.name}</SelectItem>)}</SelectContent></Select></Field>{selectedAssignment && <div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm"><p className="font-semibold">Asignación seleccionada</p><p className="mt-1">{selectedAssignment.teacher.name} · {selectedAssignment.area.name} · {selectedAssignment.group.name}</p><p className="mt-1 text-xs text-muted-foreground">Estos datos son administrados por la asignación.</p></div>}<Field label="Día"><Select value={String(entryForm.weekday)} onValueChange={(value) => setEntryForm({ ...entryForm, weekday: Number(value) })}><SelectTrigger><SelectValue placeholder="Selecciona un día" /></SelectTrigger><SelectContent>{DAYS.filter((day) => draft.school_days.includes(day.value)).map((day) => <SelectItem key={day.value} value={String(day.value)}>{day.label}</SelectItem>)}</SelectContent></Select></Field><div className="grid grid-cols-2 gap-3"><Field label="Inicio"><Input type="time" value={entryForm.start_time} onChange={(event) => setEntryForm({ ...entryForm, start_time: event.target.value })} /></Field><Field label="Fin"><Input type="time" value={entryForm.end_time} onChange={(event) => setEntryForm({ ...entryForm, end_time: event.target.value })} /></Field></div><Field label="Aula"><Select value={entryForm.aula_id} onValueChange={(value) => setEntryForm({ ...entryForm, aula_id: value })}><SelectTrigger><SelectValue placeholder="Selecciona un aula" /></SelectTrigger><SelectContent>{catalog.aulas.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field><div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={() => { setEntryForm(null); setEditingEntryId(null); }}><X className="h-4 w-4" />Cancelar</Button><Button className="flex-1" onClick={saveEntry} disabled={entryMutation.isPending}><Check className="h-4 w-4" />Guardar</Button></div></div> : <p className="text-sm text-muted-foreground">Selecciona “Agregar entrada” para programar una asignación.</p>}</CardContent></Card>
      </div>
      <Card><CardHeader><CardTitle className="text-base">Disponibilidad por grupo</CardTitle><CardDescription>Restricciones operativas heredadas del horario publicado.</CardDescription></CardHeader><CardContent className="space-y-2">{draft.availability_windows.length === 0 ? <p className="text-sm text-muted-foreground">No hay ventanas configuradas.</p> : draft.availability_windows.map((window) => <div key={window.window_id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><span className="font-medium">{window.group?.name || window.group_id}</span><span className="text-sm text-muted-foreground">{window.start_time} – {window.end_time}</span></div>)}</CardContent></Card>
      <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => saveSettingsMutation.mutate()} disabled={saveSettingsMutation.isPending}><Save className="h-4 w-4" />Guardar configuración</Button><Button onClick={() => publishMutation.mutate()} disabled={publishMutation.isPending || entries.length === 0}><Send className="h-4 w-4" />Validar y publicar</Button></div>
    </>}
    {!schedule && !schedulesQuery.isLoading && <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">No hay horario para este año. Crea un borrador después de preparar las asignaciones docentes.</CardContent></Card>}
  </div></DashboardLayout>;
};

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <div className="space-y-2"><Label>{label}</Label>{children}</div>;
export default ScheduleManagementPage;
